# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Gau < Formula
  desc "A completely optional package manager for Godot Addons."
  homepage "https://github.com/alikznollet/godot-addon-updater"
  version "0.0.1"

  on_macos do
    on_intel do
      url "https://github.com/Alikznollet/godot-addon-updater/releases/download/v0.0.1/gau_Darwin_x86_64.tar.gz"
      sha256 "7314ed67b63defa9f6dcb64db2cf58c55a01b009f575f61ab56b0708c722da29"

      def install
        bin.install "gau"
      end
    end
    on_arm do
      url "https://github.com/Alikznollet/godot-addon-updater/releases/download/v0.0.1/gau_Darwin_arm64.tar.gz"
      sha256 "4612acfe700ef02a5db564cd431e305e735bdd993688b3c9cc469f94381cf768"

      def install
        bin.install "gau"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/Alikznollet/godot-addon-updater/releases/download/v0.0.1/gau_Linux_x86_64.tar.gz"
        sha256 "a6abfe97085ced2e0e63a4b5fcf72d5eeeb7fe52a37e156ea6bda1441bea2ac2"

        def install
          bin.install "gau"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/Alikznollet/godot-addon-updater/releases/download/v0.0.1/gau_Linux_arm64.tar.gz"
        sha256 "fd768cc1485b27d14a7e1776ccdaf96de55c9812d302d5c9c4b0ad1aadf81788"

        def install
          bin.install "gau"
        end
      end
    end
  end
end
