# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Wisp < Formula
  desc "A completely optional package manager for Godot Addons."
  homepage "https://github.com/alikznollet/godot-wisp"
  version "0.1.1"

  on_macos do
    on_intel do
      url "https://github.com/Alikznollet/godot-wisp/releases/download/v0.1.1/wisp_Darwin_x86_64.tar.gz"
      sha256 "9bc18f3f575da85b60ab530fb613dba65436ce405e68a2d69314addd3bb8283e"

      def install
        bin.install "wisp"
      end
    end
    on_arm do
      url "https://github.com/Alikznollet/godot-wisp/releases/download/v0.1.1/wisp_Darwin_arm64.tar.gz"
      sha256 "95c912b2094a6816122c4d38ab8128387953c8d31922232b873b9793fcec52c5"

      def install
        bin.install "wisp"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/Alikznollet/godot-wisp/releases/download/v0.1.1/wisp_Linux_x86_64.tar.gz"
        sha256 "a261e8b1366a86b7a358250e8a322763cc6c4b3132cf4d570581724f2ce06c2e"

        def install
          bin.install "wisp"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/Alikznollet/godot-wisp/releases/download/v0.1.1/wisp_Linux_arm64.tar.gz"
        sha256 "4824541ee2c543ebb5f575db42df92d68f95a5a851a6a177f4cd96391f466529"

        def install
          bin.install "wisp"
        end
      end
    end
  end
end
